site_name: Cascade VAD
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
repo_url: https://github.com/xucailiang/cascade
repo_name: xucailiang/cascade

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API Reference:
    - Processor: api/processor.md
    - Types: api/types.md
    - Backends: api/backends.md
  - Developer Guide:
    - Contributing: dev/contributing.md